language: objective-c

before_install:
  - brew update
  - brew install libusb --without-runtime-logging
  - brew install doxygen graphviz

tags:
  only:
    - BBBlfs-osx_v0.1.0

script:
  - ./autogen.sh
  - ./configure
  - make

after_success:
  - cd bbblfs-codeless-kext
  - xcodebuild build
  - pkgbuild --analyze --root ./Build/Release/ bbblfs-codeless.plist
  - pkgbuild --install-location /System/Library/Extensions --root ./Build/Release/ --scripts ./scripts --component-plist bbblfs-codeless.plist bbblfs-codeless-kext.pkg
  
  deploy:
  provider: releases
  api-key: e246f674ee2abc04bd1434c31a9ff770712799ed
  file: bblfs-codeless-kext.pkg
  skip_cleanup: true
  on:
    tags: true
