language: objective-c

before_install:
- brew update
- brew install libusb --without-runtime-logging
- brew install doxygen graphviz

branches:
  only:
  - osx

script:
- "./autogen.sh"
- "./configure"
- make

after_success:
- cd bbblfs-codeless-kext
- xcodebuild build
- pkgbuild --analyze --root ./Build/Release/ bbblfs-codeless.plist
- pkgbuild --install-location /System/Library/Extensions --root ./Build/Release/ --scripts
  ./scripts --component-plist bbblfs-codeless.plist bbblfs-codeless-kext.pkg

before_deploy:
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from Travis-CI for build $TRAVIS_BUILD_NUMBER"
  - git add bbblfs-codeless-kext.pkg
  - git add bbblfs-codeless.plist
  - git push -q https://$GITPERM@github.com/moto-timo/BBBlfs --tags
  - ls -R

deploy:
  provider: releases
  api_key: $GITPERM
  file: bbblfs-codeless-kext.pkg
  on:
    repo: moto-timo/BBBlfs
    branch: osx
env:
  global:
  - secure: HnUFh/+rM7FOT5ZnYeqcYGr0FHV3NdNxo6f8iEMo3SMVfHjwt7EKPNrEkuRUIenrRGJt5+D1BLWSOMMUjadPpIZyE7We6KyaM84MPsZuyNi2zOV6/ytVOPSq4zj91YVcdcE7/jg1Ok0fMu+WiSNAmju2wl2X/NnYT5o60bV/9RIe0qWGAvaqc1RqLO1EFziIEtRDLYIgvgneSAehQ1rgl1FXnQg/p+79HnTvVUCN986YMC0vndqXPQJ1a59xe7A32fPwgN5eTNiq/C1sXhGQZb8LauOAubpTFK5RDxoK8arb4CDqDzwbdZK7CzPJKkCOgK3/PqgG74aSS5yQlGU4gh1x5/ds02IndKG57qy6AS7EvIJkjVGybrhwT1mWo25xVnS+e9jrbLkibFBJ5AmsTgnz5rWs86ee1bbqY6/qlrpACXduFnr0ZtrBno+mDBVQFB3qEvJWv2auhxNbtVcO2MQ850WSyq0eTx+LK4b5qqAojZGmR1wXP9+z7s9MoDFCwBL6nuDgtCgo+B4Bkp/Pm4N/yX9l10VFAVsBDt/i4qRxVDHbdcTX9gPG1qWsHuK6pG5C4hFYmaKl111baeBl0GOppGvPuzVmiJx8zGGRDU2Ls+GxJBfhMM43wkdADqdYhqf6Vn/dOZBBPj3RZYynYaoqbFLCC/E0OLd1FGJMd04=
